#adicionando um comentario
resources:
- name: hello-repo
  type: git
  source:
    uri: https://github.com/gabriel-mendes-velasco/concourse-testing.git
    branch: main

jobs:
- name: say-world
  public: true
  plan:
    - get: hello-repo
    - task: making-world
      config: 
        platform: linux
        image_resource:
          type: docker-image
          source: 
            repository: busybox
        inputs: 
          - name: hello-repo
        run:
          path: /bin/sh
          args: 
            - -c
            - |
              echo "Listando o dir"
              ls -la
              echo "Executando o script hello.sh"
              cat hello-repo/hello.sh